name: Java CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew youshallnotpass check
      - name: Check arspell plugin usage with groovy
        working-directory: ./porflavor-gradle-plugin-test/groovy/
        run: ./gradlew assembleBrand1StagingDebug --no-daemon
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)